name: Global SWAI
description: "Global Startup Weekend on Artificial Intelligence"
baseurl: ""
url: "https://gswai.github.io"
download: ""
social:
  github: 
  email: 
  facebook:
  twitter: 
  instagram:
  tumblr:
author:
  name: 
  bio: 
  email: 
  image: 
  github: 
  facebook: 
  twitter: 
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
