title: Global Startup Weekend on Artificial Intelligence
description: "GSWAI help communities educate on AI, democratize it and push them out of their comfort zone to build the better tomorrow in 54 hours"
baseurl: ""
url: "https://globalswai.co"
download: ""
social:
  name: Global SWAI
  links:
    - https://twitter.com/GlobalSWAI
    - https://www.facebook.com/GlobalSWAI
    - https://www.linkedin.com/company/globalswai
    - https://github.com/gswai
    - https://www.instagram.com/global_swai
author:
  name: Global SWAI 
  image: /assets/logo_small.png
  github: https://github.com/gswai
  facebook: https://www.facebook.com/GlobalSWAI
  twitter: https://twitter.com/GlobalSWAI
  instagram: https://www.instagram.com/global_swai
  email: globalswai@gmail.com
  show_on_post: true
twitter:
  username: GlobalSWAI 
  card: summary
logo: /assets/logo_small.png
lang: en_US
google_analytics: UA-121112808-1
google_site_verification: kf1slUKwLAkQ-vRpG27Je3Gy4FY3NC1dRvt_1Dj70zg

permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
